### ISSUE TITLE
Stashed enhancements for Rev. Q

### ISSUE THREAD

**Issue by rfrht** [rfrht/FT991A-PAT#12]
* Better Silk-Screen Pin 1 markings for Power regulators
* Larger footprint for 2SC5086
* Moving 0.1µF transistor caps away from RF section
* Lots of re-routing
* Changing 1 nF caps to Low ESL type and 0805 footprint for better RF performance
* Labeled a few signals in Eagle file for better understanding of signal route/path

**Comment by rfrht** [comment]
Repositioning J310 JFET in order to avoid the Vin line crossing the signal lead

**Comment by rfrht** [comment]
Currently examining the quantity of resistors and attenuation. Something to be tested with Revision P and if something noteworthy is found, implement in Revision Q.

**Comment by elumspe** [comment]
The part **MMBFJ310CT-ND** is marked as an obsolete item on Digi-key. 

There are three suggested substitutes: **MMBFJ310LT1G**, **MMBFU310LT1G**, and **MMBFJ310LT3G**.

The footprint looks same. Could you take a look which one will be a good direct replacement?

**Comment by rfrht** [comment]
> The part **MMBFJ310CT-ND** is marked as an obsolete item on Digi-key.
> 
> There are three suggested substitutes: **MMBFJ310LT1G**, **MMBFU310LT1G**, and **MMBFJ310LT3G**.
> 
> The footprint looks same. Could you take a look which one will be a good direct replacement?

Thank you *very* much for pointing! I have updated the BOMs to the new J310 part!

I appreciate a lot your review and feedback!

Will now create a new issue for the Attenuation and resistor tests. My VNA & oscilloscope aren't readily available here; and will file a new issue for the tests.

**Comment by rfrht** [comment]
> Currently examining the quantity of resistors and attenuation. Something to be tested with Revision P and if something noteworthy is found, implement in Revision Q.

Tracking in #14

**Comment by rfrht** [comment]
- New J130 Part Number in BOM
- Added a Ground Pad
- Slight change in resistors for a slight gain (0.3 dB) in amplification (see #14)
