### ISSUE TITLE
Missing installation image

### ISSUE THREAD

**Issue by halsteaw** [rfrht/FT991A-PAT#15]
On the page

https://github.com/rfrht/FT991A-PAT/wiki/installation

the image link for the TX9 tap point located at

https://github.com/rfrht/FT991A-PAT/blob/PAT-Light/Design/tx9.jpg

is missing.

**Comment by rfrht** [comment]
Thank you **very** much for pointing, @halsteaw . I have fixed the URL and the image now renders correctly!
