### ISSUE TITLE
Error in Wiki: SHIFT Menu Item Description

### ISSUE THREAD

**Issue by 4andy2001** [rfrht/FT991A-PAT#19]
In the SHIFT menu item description, RX or TX field (see below), it should say RX, not TX:

SHIFT

    WHAT: The shift function "shifts" (doh again) your receiving bandpass to above or below (or left or right), removing either the bass or treble part of the signal depending to the direction that you set the shift - narrowing the received signal.
    AVAILABLE OPTIONS: -1200 Hz to +1200 Hz. 0 means no shift, disabled. Set with "Multi" encoder.
    **_RX or TX? TX_**
    WHICH MODE? AM, SSB, CW
    WHEN TO USE: The primary use is to defend from an adjacent signal over the lower or higher edge of your receiving signal. Use shift to dodge this interfering signal.
    CAVEAT: This is also useful to make the receiving less tiring, irrespective of having or not an interfering signal - Try using Shift between -600 and -200 together with DNR - I promise you will love it!

**Comment by rfrht** [comment]
Hello @4andy2001 
Thank you **very** much for pointing it! I have just fixed it!

Thanks again and happy holidays!

**Comment by 4andy2001** [comment]
My pleasure.  

Found your wiki very helpful bringing up digital modes on my rig-appreciate the effort you put into it.

Happy holidays!
